version: "3"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    command: ["npm", "start"]

  socket:
    build:
      context: ./socket
    ports:
      - "4001:4001"
    command: ["npm", "start"]
