version: "3"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    command: ["npm", "start"]

  socket:
    build:
      context: ./socket
    ports:
      - "4003:4003"
    command: ["npm", "start"]

  postgres:
    image: postgres:latest

    healthcheck:
      test: ["CMD", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 21222324
      POSTGRES_DB: twit_server

    ports:
      - "5432:5432"
    volumes: # Define the volume here
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: # Define the volume name here
